### ISSUE TITLE
Sometimes there are frame drops at the start of the swipe gesture when using react-native-screens

### ISSUE THREAD

**Issue by ssssssssssss** [react-navigation/react-navigation-stack#19]
I've experimented stack navigator with the new native 'screens', but found it would be too aggressive to set the previous screen to inactive which makes the swipe back janky. Shall we just keep the most recent 2 screens active instead?

**Comment by brentvatne** [comment]
cc @kmagiera - I think what @ssssssssssss is referring to here is that when you go to swipe back there is a brief period where sometimes frames are dropped as the previous screen becomes active again

**Comment by brentvatne** [comment]
oh also, I don't think that showing the 2 most recent screens active is a good solution @ssssssssssss - this diminishes some of the key benefits of using react-native-screens to begin with because the previous screen won't receive native view lifecycle events then

**Comment by kmagiera** [comment]
Hey @ssssssssssss ! What's the version of screens you tried? Do you observe this on iOS or android or both? Are you using Expo or not? Can you only notice this when running on device or also emulators? Can you make a sample app that would help to reproduce this issue?

**Comment by brentvatne** [comment]
closed due to inactivity
