### ISSUE TITLE
Warning: blurTextInput is deprecated, user `Keyboard.dismiss` of the `blur` method of the `TextInput` ref.

### ISSUE THREAD

**Issue by Strate** [react-navigation/react-navigation-stack#38]
Trying to go back or forward, when keyboard visible triggers warinig:
```
blurTextInput is deprecated, user `Keyboard.dismiss` of the `blur` method of the `TextInput` ref.
```

**Comment by brentvatne** [comment]
you need to provide more information to reproduce this. i don't know where this code is coming from as there is no call to `blurTextInput` in react-navigation-stack

**Comment by Strate** [comment]
@brentvatne this happpens in react-navigation/src/navigators/createKeyboardAwareNavigator, seems I mixed up packages. Gonna to open issue there.
