### ISSUE TITLE
react-navigation v3.0.0-alpha.12  StackNavigatorConfig.navigationOptions.headerStyle is ignored

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/react-navigation-stack#43]
react navigation v2
![img_0485](https://user-images.githubusercontent.com/1118249/47401857-86f2ba80-d775-11e8-9abc-c080817bb677.PNG)
react navigation v3.0.0-alpha.12 
![img_0484](https://user-images.githubusercontent.com/1118249/47401864-8bb76e80-d775-11e8-8c37-2df492f8afcf.PNG)

**Comment by brentvatne** [comment]
this is a result of an api change that we haven't documented yet due to this just being alpha still, see below:

```js
const Example = createStackNavigator({
  SomeRoute: A,
  OtherRoute: B,
}, {
  navigationOptions: {}, // this is now the navigationOptions for Example
  defaultNavigationOptions: {}, // these are the default navigationOptions for SomeRoute and OtherRoute
})
```

basically, change `navigationOptions` on your navigator config object to `defaultNavigationOptions`
