### ISSUE TITLE
react navigation v3.0.0-alpha.14 gesturesEnabled  not working for android 

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/react-navigation-stack#46]

**Comment by brentvatne** [comment]
I disabled gestures on Android: https://github.com/react-navigation/react-navigation-stack/blob/0e302b3ceafd80d12295af41dfa4a7c7930c18d7/src/views/StackView/StackViewLayout.js#L281-L307

I guess I shouldn't have done that, I'll revert it back

**Comment by franckmaurin** [comment]
Hi @brentvatne, did you reverted ? GesturesEnabled seems still not working for android.

**Comment by brentvatne** [comment]
hey @franckmaurin can you create a new issue to explain what you mean by that? thanks!
