### ISSUE TITLE
animatedStyle might be null, causing crash

### ISSUE THREAD

**Issue by jlongster** [react-navigation/react-navigation-stack#64]
I updated to react-navigation 3 and have a crash. Don't know exactly the situation that causes this, but the bug is clear in the code.

Here it creates a `style` variable that might be false: https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewLayout.js#L810-L818

It then passes it down to the `Card` component as the `animatedStyle` prop: https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewLayout.js#L836

In `Card`, it assumes `animatedStyle` is an object and destructures it: https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewCard.js#L45-L49

Locally I fixed by making it default to an empty object, not sure what you want to do.

**Comment by jlongster** [comment]
This seems like a fairly major issue? Or is `screenInterpolator` usually not null? I'm not sure why it is in my case, but I have a fairly complex setup. Has anyone read my issue above? I can open a PR, should be a quick fix just tell me which side to do it on (default to empty object where it uses `screenInterpolator`?)

**Comment by brentvatne** [comment]
hey @jlongster! ah the beauties of working in an untyped codebase sometimes :P thanks for the investigation, will fix this for you shortly

**Comment by brentvatne** [comment]
used the same fix you made locally and released 3.0.4. it is indeed valid for `screenInterpolator` to be null but that is usually not the case, I hadn't considered that but I can see not why you might want to do it.

**Comment by jlongster** [comment]
Awesome, thanks!
