### ISSUE TITLE
transparentCard prevents from header height being taken into account

### ISSUE THREAD

**Issue by levibuzolic** [react-navigation/react-navigation-stack#65]
Setting `transparentCard: true` results in the header overlapping the content of a stack due to `paddingTop` being applied to the parent of the absolutely positioned View in [StackViewCard.js](https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewCard.js#L70).

You can see this in action in this [Snack](https://snack.expo.io/@levibuzolic/stack-transparentcard-padding-issue).

`transparentCard: false` | `transparentCard: true`
---|---
![img_1489](https://user-images.githubusercontent.com/721323/49059020-e94e4780-f25a-11e8-8d33-73661da862e6.PNG) | ![img_1488](https://user-images.githubusercontent.com/721323/49059022-eb180b00-f25a-11e8-8481-9751393cbdb0.PNG)

**Comment by levibuzolic** [comment]
I'm wondering if the potential solution would be to change `paddingTop` to `top` as the styles are applied to an `StyleSheet.absoluteFill` view anyway. 🤔

**Comment by brentvatne** [comment]
it's unclear to me why you would ever want a header in this situation but there is no harm done by the change that makes this possible :) deployed in react-navigation@3.0.3 / react-navigation-stack@1.0.3

**Comment by levibuzolic** [comment]
Thanks @brentvatne -- our use case is pretty non-standard, but we're using it to allow us to show a semi-transparent blurview with a card-style interface.

![img_1547](https://user-images.githubusercontent.com/721323/49345514-19be3780-f6da-11e8-9093-3ea44ba2fa84.PNG)

**Comment by brentvatne** [comment]
looks nice :)
