### ISSUE TITLE
Applying cardStyle in stackNavigator config has weird behavior

### ISSUE THREAD

**Issue by dereknelson** [react-navigation/react-navigation-stack#69]
After the background color change ([referenced here](https://github.com/react-navigation/react-navigation/issues/5253)), the left side of the background has a [white background for ~3 pixels and a weird shadow effect](http://prntscr.com/lp47r0). It's unrelated to what's being rendered on the [screen](http://prntscr.com/lp48wt).

Style applied: 
```
cardStyle: {
    flex: 1,
    backgroundColor: '#fffff',
},
```

Originally it was within a nested stack navigator, but it happens regardless of being nested. Working on reproduction.

**Comment by dereknelson** [comment]
Weird. Just tested with '#F7F7F7' and it works fine.

**Comment by brentvatne** [comment]
let me know if you can reproduce! what is happening is that you are seeing right through the card, and the sliver you see there is the result of an optimization for rendering the shadow, previously you would have just seen black
