### ISSUE TITLE
StackRouter warning 'StackRouter provided invalid state, index should always be the top route'

### ISSUE THREAD

**Issue by danielmahadi** [react-navigation/react-navigation-stack#98]
Hi Guys,

I am developing an application that allows the user to move back and forward of the screens in StackNavigation, something like the browser navigation experience. I handled the navigation state myself by extending `router.getStateForAction` of the `StackNavigator`.
And I saw a warning `StackRouter provided invalid state, index should always be the top route.`

Is this a harmless warning? Or Do I miss something here?

**Comment by ericvicenti** [comment]
It does seem like a harmless warning, but lots of behavior inside of StackRouter.getStateForAction will assume that the current index route is the top route of the stack. So unexpected things may happen in your case because you've provided it with a navigation state like this:

```
{
  index: 1, // not the last route, as would be expected
```

**Comment by danielmahadi** [comment]
Thanks for the feedback. I guess this means that I need to do rigorous tests on my end here and make sure all side-effects are cover. So far it has been working well. I am so happy with the extendability of this library, loving it :)

**Comment by SiyabongaNzulwana** [comment]
I am facing the same issue, anyone whom has a solution please share...

**Comment by dzek69** [comment]
If you came from Googling the error: just set your index to your actions array length minus one.

[a, b, c] - set it to 2
[a] - set it to 0

If you need to do something advanced - i'd rather find another library, this one is good for easy stuff
